### ISSUE TITLE
Similarity scraper does not support the discussed structure

### ISSUE THREAD

**Issue by queicherius** [peermusic/scrape-engine#2]
This does not support the discussed structure in peermusic/user-stories#24. We need to be able to send it the following payload:
- **title, album and artist** (supported, but only takes the "title" to evaluate and ignores "album" and "artist")
- **album and artist**
- **artist**
- **genre**

The `artist` functionality gives back **artists**, instead of our wanted **tracks**.

**Comment by ryomiyaichi** [comment]
Fixed, please extend music-similarity module. 2fc78f1f9fcc72a56e8fd90487f34da5691fe62a
While you are on review please check if the try-catch is would work this way.

**Comment by queicherius** [comment]
:+1:
